function weather_description = importWindDirection(filename, dataLines)
    %IMPORTFILE Import data from a text file
    %  WEATHER_DESCRIPTION = IMPORTFILE(FILENAME) reads data from text file
    %  FILENAME for the default selection.  Returns the data as a timetable.
    %
    %  WEATHER_DESCRIPTION = IMPORTFILE(FILE, DATALINES) reads data for the
    %  specified row interval(s) of text file FILENAME. Specify DATALINES as
    %  a positive scalar integer or a N-by-2 array of positive scalar
    %  integers for dis-contiguous row intervals.
    %
    %  Example:
    %  weather_description = importfile("C:\Users\Ntshuxeko.Mathebula\SAWS Workshop 2025\data\weather_description.csv", [2, Inf]);
    %
    %  See also READTIMETABLE.
    %
    % Auto-generated by MATLAB on 04-Sep-2025 09:34:30

    %% Input handling

    % If dataLines is not specified, define defaults
    if nargin < 2
        dataLines = [2, Inf];
    end

    %% Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 37);

    % Specify range and delimiter
    opts.DataLines = dataLines;
    opts.Delimiter = ",";

    % Specify column names and types
    opts.VariableNames = ["datetime", "Vancouver", "Portland", "SanFrancisco", "Seattle", "LosAngeles", "SanDiego", "LasVegas", "Phoenix", "Albuquerque", "Denver", "SanAntonio", "Dallas", "Houston", "KansasCity", "Minneapolis", "SaintLouis", "Chicago", "Nashville", "Indianapolis", "Atlanta", "Detroit", "Jacksonville", "Charlotte", "Miami", "Pittsburgh", "Toronto", "Philadelphia", "NewYork", "Montreal", "Boston", "Beersheba", "TelAvivDistrict", "Eilat", "Haifa", "Nahariyya", "Jerusalem"];
    opts.VariableTypes = ["datetime", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Specify variable properties
    opts = setvaropts(opts, ["Vancouver", "Portland", "SanFrancisco", "Seattle", "LosAngeles", "SanDiego", "LasVegas", "Phoenix", "Albuquerque", "Denver", "SanAntonio", "Dallas", "Houston", "KansasCity", "Minneapolis", "SaintLouis", "Chicago", "Nashville", "Indianapolis", "Atlanta", "Detroit", "Jacksonville", "Charlotte", "Miami", "Pittsburgh", "Toronto", "Philadelphia", "NewYork", "Montreal", "Boston", "Beersheba", "TelAvivDistrict", "Eilat", "Haifa", "Nahariyya", "Jerusalem"], "EmptyFieldRule", "auto");
    opts = setvaropts(opts, "datetime", "InputFormat", "yyyy-MM-dd HH:mm:ss", "DatetimeFormat", "preserveinput");

    % Import the data
    weather_description = readtimetable(filename, opts, "RowTimes", "datetime");

end