function city_attributes = importCityAttributes(filename, dataLines)
    %IMPORTFILE Import data from a text file
    %  CITY_ATTRIBUTES = IMPORTFILE(FILENAME) reads data from text file
    %  FILENAME for the default selection.  Returns the data as a table.
    %
    %  CITY_ATTRIBUTES = IMPORTFILE(FILE, DATALINES) reads data for the
    %  specified row interval(s) of text file FILENAME. Specify DATALINES as
    %  a positive scalar integer or a N-by-2 array of positive scalar
    %  integers for dis-contiguous row intervals.
    %
    %  Example:
    %  city_attributes = importfile("C:\Users\Ntshuxeko.Mathebula\SAWS Workshop 2025\data\city_attributes.csv", [2, Inf]);
    %
    %  See also READTABLE.
    %
    % Auto-generated by MATLAB on 04-Sep-2025 09:29:54

    %% Input handling

    % If dataLines is not specified, define defaults
    if nargin < 2
        dataLines = [2, Inf];
    end

    %% Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 4);

    % Specify range and delimiter
    opts.DataLines = dataLines;
    opts.Delimiter = ",";

    % Specify column names and types
    opts.VariableNames = ["City", "Country", "Latitude", "Longitude"];
    opts.VariableTypes = ["string", "categorical", "double", "double"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Specify variable properties
    opts = setvaropts(opts, "City", "WhitespaceRule", "preserve");
    opts = setvaropts(opts, ["City", "Country"], "EmptyFieldRule", "auto");

    % Import the data
    city_attributes = readtable(filename, opts);

end